### ISSUE TITLE
Can't extract data if Keystone v3 is used

### ISSUE THREAD

**Issue by cgimeno** [IFCA/caso#39] opened 2017-01-10 12:05 UTC
caso is not able to extract usage records if keystone v3 API is being used. https://github.com/IFCA/caso/pull/40 solves that, but be aware: this pull request drops v2 support in favour of v3.

**Comment by alvarolopez** [comment] 2017-01-13 11:05
This is solved here: https://github.com/alvarolopez/caso/commit/594f1e86f5bd0196ed79495bdaa4190a70ddd6f1

The changes are not merged back yet :-(

**Comment by alvarolopez** [comment] 2017-01-13 11:06
Duplicate of https://github.com/IFCA/caso/issues/32

**Closed by alvarolopez** 2017-01-13 11:06 UTC
Labels: bug, duplicate
